/* Single source of truth for labels, tooltips, formats, and view configs. */
export const METRICS = {
  player: { label: "Player", tip: "Display name (web_name).", fmt: "text", sticky: true },
  team: { label: "Team", tip: "Club short name.", fmt: "text" },
  pos: { label: "Pos", tip: "FPL position.", fmt: "text" },
  Cost: { label: "£m", tip: "Current-season FPL price in £m. Do not divide by 10.", fmt: "1dp" },
  apps: { label: "Apps", tip: "Appearances (minutes > 0) inside the selected GW window.", fmt: "int" },
  mins_per_app: {
    label: "Min/App",
    tip: "Average minutes per appearance across the selected season / competition / venue — not only the window.",
    fmt: "1dp",
  },
  Pts: { label: "Pts", tip: "FPL points in the selected gameweeks (player_gw, one figure per GW).", fmt: "int" },
  G: { label: "G", tip: "Goals in the window (match / Opta layer).", fmt: "int", per90: true },
  A: { label: "A", tip: "Assists in the window.", fmt: "int", per90: true },
  PenG: { label: "PenG", tip: "Penalties scored in the window.", fmt: "int" },
  xG: { label: "xG", tip: "Expected goals (Opta match layer). Distinct from FPL expected_goals.", fmt: "2dp", per90: true },
  xA: { label: "xA", tip: "Expected assists (Opta).", fmt: "2dp", per90: true },
  xGI: { label: "xGI", tip: "Expected goal involvements = xG + xA (Opta).", fmt: "2dp", per90: true },
  Sh: { label: "Sh", tip: "Total shots.", fmt: "int", per90: true },
  SoT: { label: "SoT", tip: "Shots on target.", fmt: "int", per90: true },
  CC: { label: "CC", tip: "Chances created (key passes). Big chances created is not available — CC / xA / TiB are the proxies.", fmt: "int", per90: true },
  TiB: { label: "TiB", tip: "Touches in the opposition box. A creation / threat proxy.", fmt: "int", per90: true },
  BCM: { label: "BCM", tip: "Big chances missed. Big chances created is not published at player level.", fmt: "int" },
  xGOT: { label: "xGOT", tip: "Expected goals on target (player shots).", fmt: "2dp", per90: true },
  CS: { label: "CS", tip: "Clean sheets in the window (FPL, Premier League).", fmt: "int" },
  Tkl: { label: "Tkl", tip: "Tackles (per 90 when listed as Tkl/90).", fmt: "2dp", always90: true },
  CBI: { label: "CBI", tip: "Clearances + blocks + interceptions, per 90.", fmt: "2dp", always90: true },
  DefCon: { label: "DefCon", tip: "Defensive contributions per 90.", fmt: "2dp", always90: true },
  Saves: { label: "Saves", tip: "Saves in the window.", fmt: "int", per90: true },
  GC: { label: "GC", tip: "Goals conceded.", fmt: "int", per90: true },
  xGOTf: { label: "xGOTf", tip: "On-target xG faced.", fmt: "2dp", per90: true },
  xGP: { label: "xGP", tip: "xG prevented via saves (goals_prevented).", fmt: "2dp" },
  npxG: { label: "npxG", tip: "Non-penalty xG from shots.", fmt: "2dp", per90: true },
  F3: { label: "F3", tip: "Passes into the final third.", fmt: "int", per90: true },
  Dr: { label: "Dr", tip: "Successful dribbles.", fmt: "int", per90: true },
  YC: { label: "YC", tip: "Yellow cards.", fmt: "int" },
  Aer: { label: "Aer", tip: "Aerial duels won.", fmt: "int", per90: true },
  Clr: { label: "Clr", tip: "Clearances.", fmt: "int", per90: true },
  Int: { label: "Int", tip: "Interceptions.", fmt: "int", per90: true },
  Blk: { label: "Blk", tip: "Blocks.", fmt: "int", per90: true },
  Rec: { label: "Rec", tip: "Recoveries.", fmt: "int", per90: true },
  Cr: { label: "Cr", tip: "Accurate crosses.", fmt: "int", per90: true },
  SPxG: { label: "SPxG", tip: "Set-piece expected goals.", fmt: "2dp", per90: true },
  Bon: { label: "Bonus", tip: "FPL bonus points in the selected gameweeks.", fmt: "int" },
  BPS: { label: "BPS", tip: "Bonus point system score in the selected gameweeks.", fmt: "int" },
  PS: { label: "PS", tip: "Penalties saved.", fmt: "int" },
  SiB: { label: "SiB", tip: "Saves inside the box.", fmt: "int", per90: true },
  HC: { label: "HC", tip: "High claims.", fmt: "int" },
  SW: { label: "SW", tip: "Sweeper actions.", fmt: "int" },
  GF: { label: "GF", tip: "Goals for.", fmt: "1dp" },
  GA: { label: "GA", tip: "Goals against.", fmt: "1dp" },
  xGf: { label: "xGf", tip: "Expected goals for (team).", fmt: "2dp" },
  xGa: { label: "xGa", tip: "Expected goals against (team).", fmt: "2dp" },
  ShT: { label: "Sh", tip: "Team shots.", fmt: "int" },
  SoTT: { label: "SoT", tip: "Team shots on target.", fmt: "int" },
  Poss: { label: "Poss", tip: "Possession % (average in the window).", fmt: "1dp" },
  PtsT: { label: "Pts", tip: "League points (3/1/0) in the window.", fmt: "int" },
  CST: { label: "CS", tip: "Team clean sheets in the window.", fmt: "int" },
};

export const METRIC_GROUP_LABELS = {
  creativity: "Creativity",
  threat: "Threat",
  defending: "Defending",
  fpl: "FPL metrics",
};

export const VIEWS = {
  attackers: {
    page: "attackers",
    positions: ["Forward", "Midfielder"],
    columns: ["player", "team", "pos", "Cost", "apps", "Pts", "G", "xG", "npxG", "A", "xA", "xGI", "CC", "SoT"],
    metricGroups: {
      creativity: ["Dr", "F3", "Cr"],
      threat: ["SPxG", "xGOT", "Sh", "TiB", "BCM"],
      defending: ["DefCon", "CBI", "Tkl", "Rec"],
      fpl: ["Bon", "BPS", "YC"],
    },
    defaultSort: "xGI",
    defaultDir: "desc",
    per90Keys: ["G", "A", "xG", "xA", "xGI", "Sh", "SoT", "CC", "TiB", "xGOT", "npxG", "F3", "Dr", "Cr", "SPxG", "Rec"],
    always90Keys: ["Tkl", "CBI", "DefCon"],
    minMinsDefault: 60,
    positionFilter: true,
  },
  defenders: {
    page: "defenders",
    positions: ["Defender"],
    columns: ["player", "team", "pos", "Cost", "apps", "Pts", "CS", "GC", "DefCon", "G", "xG", "A", "xA", "xGI", "CC", "SoT"],
    metricGroups: {
      creativity: ["Dr", "F3", "Cr"],
      threat: ["SPxG", "xGOT", "Sh", "TiB", "BCM"],
      defending: ["Clr", "Blk", "Int", "Tkl"],
      fpl: ["Bon", "BPS", "YC"],
    },
    defaultSort: "DefCon",
    defaultDir: "desc",
    per90Keys: ["G", "A", "xG", "xA", "xGI", "CC", "SoT", "Dr", "F3", "Cr", "SPxG", "xGOT", "Sh", "TiB", "Clr", "Blk", "Int", "GC"],
    always90Keys: ["Tkl", "DefCon"],
    minMinsDefault: 60,
  },
  gk: {
    page: "gk",
    positions: ["Goalkeeper"],
    columns: ["player", "team", "pos", "Cost", "apps", "Pts", "CS", "GC"],
    metricGroups: {
      defending: ["Saves", "SiB", "xGOTf", "xGP", "PS"],
      fpl: ["Bon", "BPS", "YC"],
    },
    defaultSort: "Pts",
    defaultDir: "desc",
    per90Keys: ["Saves", "GC", "xGOTf", "SiB"],
    always90Keys: [],
    minMinsDefault: 60,
  },
  teams: {
    page: "teams",
    columns: ["team", "apps", "PtsT", "GF", "GA", "xGf", "xGa", "ShT", "SoTT", "Poss", "CST"],
    extraColumns: [],
    defaultSort: "xGf",
    defaultDir: "desc",
    minMinsDefault: 0,
    directMetrics: true,
    hideSearch: false,
    hideMins: true,
    hidePer90: true,
    hideDetail: true,
    hidePlayers: true,
    hideCost: true,
  },
};

export const STORAGE_KEY = "fplpulse.v4";
export const PLAYER_WINDOWS = Array.from({ length: 38 }, (_, i) => i + 1);
export const INSIGHT_WINDOWS = Array.from({ length: 10 }, (_, i) => i + 1);
export const MIN_MINS_OPTIONS = [0, 30, 45, 60, 70, 80];
export const FDR_URL = "https://premierfantasytools.com/fpl-fixture-difficulty/";
